# Generated by Django 4.2.3 on 2023-07-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_user_confirm_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price1m', models.CharField(max_length=100)),
                ('price3m', models.CharField(max_length=100)),
                ('price6m', models.CharField(max_length=100)),
                ('price1y', models.CharField(max_length=100)),
                ('price2y', models.CharField(max_length=100)),
                ('price3y', models.CharField(max_length=100)),
                ('sites', models.CharField(max_length=100)),
                ('space', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('panel', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('ssh', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='bvuiadickl@example.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='passwd',
            field=models.CharField(default='w3NcPbAB', max_length=100),
        ),
    ]
