# Generated by Django 4.2.3 on 2023-07-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_tarifs_alter_user_email_alter_user_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='dsuehwnztr@example.com', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passwd',
            field=models.CharField(default='KADKnCCZ', max_length=100),
        ),
    ]
